## Basic Configuration

baseurl = "https://elegant-booth-db408f.netlify.app"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = ""
title = ""
theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "" # Comment out to disable Disqus.
googleAnalytics = "UA-168747617-1"
enableRobotsTXT = true

## Site Settings
[params]
author = ""
intro = ""
description = ""
authorimage = ""
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = ""
keywords = ""

## Social Accounts
#[params.social]
#github = "<username>"
#twitter = "<username>"


## Extras
[params.extra]
copyright = "2020 © SCIP Unimelb. All rights reserved."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
